name: Update dataset

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC

  # Allows us to run the workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Download CORDIS HORIZON dataset
        run: |
          mkdir source/
          cd source/
          wget https://cordis.europa.eu/data/cordis-HORIZONprojects-xml.zip
          unzip cordis-HORIZONprojects-xml.zip
