name: Update dataset

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight UTC

  # Allows us to run the workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cd models/rust && cargo build --release

      # - name: Cache Cordis Data
      #   id: cache-cordis
      #   uses: actions/cache@v4
      #   with:
      #     path: download
      #     key: ${{ runner.os }}-cordis

      - name: Download dataset
        run: scripts/download.sh

      - name: Update dataset
        run: scripts/update.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
